name: Access Secret

on:
  push:
    branches:
      - main

jobs:
  access-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access Secret
        env:
          API_KEY: ${{ secrets.API_KEY }}